# Generated by Django 3.0.10 on 2020-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
